# Generated by Django 5.0 on 2023-12-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INFOList',
            fields=[
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
